### ISSUE TITLE
isOver vs getDimensions Coords

### ISSUE THREAD

**Issue by eriklott** [gdotdesign/elm-dom#2]
Is there any reason for the `getDimensions` func to return  dimensions relative to the viewport (expected) while the `isOver` func accepts a position relative to the page? I sort of expected `isOver` to accept a position relative to the viewport.

**Comment by gdotdesign** [comment]
There is no specific reason for it. It's probably because most of the time the position comes from the a `MouseEvent` and it doesn't have coordinate for the viewport but it has for the page (`pageX`). 

I agree that it's inconsistent, I'm open for suggestions on how the resolve it, I have some possible solutions:
* use either page or viewport for both and let the user handle the other
* make two versions of these functions one for the viewport and one for the page

Let me know what you think.

**Comment by eriklott** [comment]
Yeah - that makes sense. Just keep it as it is for now. Until the `Mouse` package accepts custom decoders, developers won't have direct access to the `clientX` and `clientY` values.  

In the mean time, we've wrapped your `isOver` function in our own so that it accepts clientX and clientY because this is what we use locally.

Thanks for the quick response.
